### ISSUE TITLE
Integrate with the official repo

### ISSUE THREAD

**Issue by Keith94** [totallymike/contextPlus#1]
Rather than having a separate add-on to switch contexts, can this feature be added to the official Containers Experiment add-on (through a PR if accepted?). Or, do you plan on adding more features related to container tabs?

**Comment by totallymike** [comment]
Interesting.  I'm not familiar with the addon.  After googling for a few minutes, I find this: https://github.com/mozilla/testpilot-containers.  Is it what you're referring to?

Also, how does it coexist with the built-in container functionality? It appears, at least at a glance, to be made redundant by the built-in functionality.

As for additional functionality, I'm not sure yet :)

One thing I'd like to do eventually is basically what I've got already, but in bulk.  That will require some form of UI to select multiple tabs, but I haven't gotten around to fleshing out the concept yet.

**Comment by Keith94** [comment]
>After googling for a few minutes, I find this: https://github.com/mozilla/testpilot-containers. Is it what you're referring to?

Yes, that's the one. This experiment has another UI and additional features like a) sort containers b) hide container or c) move container to a new window. It can be installed [here](https://testpilot.firefox.com/experiments/containers).

The ability to move a default tab to container tab is being discussed here: https://github.com/mozilla/testpilot-containers/issues/311. Maybe the devs at Mozilla would accept a pull request for it, but I'm not sure. :)

**Comment by totallymike** [comment]
I'd be glad for this functionality to end up in that plugin. It does seem like a nice extension, and I like the way it lets you organize tabs by container. I haven't had the bandwidth to look into adding this to it yet, but it seems like a worthy place for it to go.

**Comment by jonathanKingston** [comment]
I doubt this will happen, I think they should be offered separate personally so users can "opt in" explicitly by installing this.

**Comment by jonathanKingston** [comment]
As an update to latest changes in Nightly.

- Containers now can be monitored with events https://bugzilla.mozilla.org/show_bug.cgi?id=1344519
- https://bugzilla.mozilla.org/show_bug.cgi?id=1389265 promises for the apis will now reject rather than resolve null and false.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1354602 containers will now be enabled for all your users as you have the permission.

This basically makes this bug not important, out test pilot addon, is just an interface like yours is. Installing either will give users container features.

Let me know if you need any support of have questions 👍

**Comment by totallymike** [comment]
I noticed that containers were enabled by default in nightly now! Very vice 👍 
I'll look through the rest of this stuff.  Thanks for the update.
